name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Copy example-notebooks repository
        run: git clone https://github.com/dandi/example-notebooks

      - name: Install version of Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install requirements
        run: pip install -r requirements.txt

      # - name: Correct gcc error
      #   run: sudo apt-get install gcc python3-dev

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
