name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Copy example-notebooks repository
        run: |
          git clone https://github.com/dandi/example-notebooks
          mv ./example-notebooks ./docs/
      - run: ls -la ./docs/example-notebooks
      - name: Deploy docs
        uses: kabilar/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
